### ISSUE TITLE
Link to categories

### ISSUE THREAD

**Issue by danielparas** [fruitstudios/LinkIt#10]
Is it possible to link to categories? (can't seem to find any reference to this functionality). If not how hard is it to add it please? I'd be happy to help with it :)

**Comment by samhibberd** [comment]
Sure thing, its been on the list for a while, will see if I can get it looked at today.

**Comment by samhibberd** [comment]
Done, hope this helps, let me know if you run into any issues.

**Comment by danielparas** [comment]
Great, thanks a lot! Appreciate it

**Comment by ben-callaway** [comment]
Hello,

I'm out of the office today, back Monday 2nd March. All emails will be dealt with on my return.

If you do have anything urgent, please don’t hesitate to get in contact with Sam on 01962 809 103 | sam@fruitstudios.co.uk.

Thank you.

Kind regards,
Ben Callaway
 
Fruit Studios Ltd
First Floor
100 High Street
Winchester
Hampshire
SO23 9AH
 
T: 01962 809 103 
E: ben@fruitstudios.co.uk
W: www.fruitstudios.co.uk

====================================================

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify Fruit Studios Ltd immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Fruit Studios Ltd does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. Opinions expressed in this email are those of Ben Callaway, and do not necessarily reflect those of Fruit Studios Ltd. If verification is required please request a hard-copy version.

====================================================
