### ISSUE TITLE
Single option version doesn't display the field on a new entry

### ISSUE THREAD

**Issue by joshangell** [fruitstudios/LinkIt#11]
I can't get this to show the field if only one Link Type is selected, such as email.

I have made it work by adding the following code at line 23 of templates/_fieldtype/input.html:

      {% else %}

		{% if type is null %}
			{% for key,value in types %}
				{% set type = key %}
			{% endfor %}
		{% endif %}

		<input type="hidden" name="{{ name }}[type]" value="{{ type }}" />

This sets the type to the only valid type in the types array and therefor allows the field to be used, however it doesn't let you save the field empty.

I may be mis-using the plugin here but I basically want it to just validate an email field in this scenario and am using it elsewhere so didn't want to install a different plugin for just that purpose.

**Comment by samhibberd** [comment]
Hi,

I am out of the office on holiday returning Tuesday 3rd of March. All emails will be dealt with on my return.

If you do have anything urgent please don’t hesitate to get in contact with Ben on 01962 809 103 or ben@fruitstudios.co.uk.

Thank you.

Kind regards,

Sam Hibberd
 
Fruit Studios Ltd
First Floor
100 High Street
Winchester
SO23 9AH
 
====================================================

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify Fruit Studios Ltd immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Fruit Studios Ltd does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. Opinions expressed in this email are those of Sam Hibberd, and do not necessarily reflect those of Fruit Studios Ltd. If verification is required please request a hard-copy version.

====================================================

**Comment by samhibberd** [comment]
I will take a look for you, if you are looking for simple field validation I built Custom Validation for just that, simple validation rules added to plain text fields:

https://github.com/fruitstudios/CustomValidation

**Comment by danielparas** [comment]
I am experiencing a similar issue. Only happens when a single link type is selected.

**Field Config**
![screen shot 2015-03-03 at 17 32 28](https://cloud.githubusercontent.com/assets/5887801/6466958/76d81226-c1cb-11e4-9143-6c744a428129.png)

**Entries Editor** (missing the field to put in custom URL)
![screen shot 2015-03-03 at 17 32 54](https://cloud.githubusercontent.com/assets/5887801/6466957/76bed8b0-c1cb-11e4-88e5-5ae7ecd57151.png)

**Comment by samhibberd** [comment]
Will get this fixed today!

**Comment by joshangell** [comment]
Hey Sam - thanks for this! Not sure how I missed your other plugin as it covers what I need for a bunch of things, and this one works great for my multi-option link fields.

Thanks!

**Comment by samhibberd** [comment]
Just released a fix for this.

**Comment by joshangell** [comment]
Thanks Sam!

**Comment by danielparas** [comment]
Thanks Sam for the quick fix! The custom text field is now showing for single link types but it's not saving for some reason :( (fields keep returning "false"). As soon as I add another type to get the dropdown showing again, saving works.

**Comment by samhibberd** [comment]
Fixed :)

**Comment by danielparas** [comment]
Perfect thanks a lot!
