### ISSUE TITLE
Entry LinkIt field not reading defined entries.

### ISSUE THREAD

**Issue by ChaseGiunta** [fruitstudios/LinkIt#13]
I'm able to select an entry, save the entry I'm in (saving the entry value I chose), but upon returning to the entry again, the field is cleared. This of course will not let me save due to validation.

![image](https://cloud.githubusercontent.com/assets/1377169/7544242/fe14c164-f590-11e4-96f9-c9e6cdf89573.png)

**Comment by samhcorney** [comment]
Hi Chase,

I tried the following...

1) Added a link it field to the entry I'm working on.

2) Clicked through to edit the entry from (1)

3) Added a 'linkit' link in the entry which links to a separate entry.

4) Saved the entry.

5) Clicked back through to the entry to check for any issues.

I wasn't able to recreate your issue using the above. Talk me through what your doing and I'll give it another go!

Have you changed any of the default link it field type settings from the edit field type page... craft->fields->Link It?

Thanks,

Sam

**Comment by ChaseGiunta** [comment]
That seems to be what I'm doing. 
Would the fact that I'm on a multi-locale site be an issue with reading the entry value?
Initially I had the "This field is translatable" checked, but after unchecking, the problem still exists.

I'm only toggling Custom URL & Entry for the link types allowed. Using only one source for Entry Sources. Seems to work as desired except for not being able to read/display the values from the db once I go back into the entry.

**Comment by superflausch** [comment]
Hi there,

I'm having the same issue with a new project I'm working on.

I have a page/entry where I add a LinkIt field. Assign an entry to the link and save the entry. Works as expected on the front-end/DB, but as soon as I open the page/entry again in the CP the LinkIt field looses the assigned entry (type entry is still selected but no entry is selected). When I try to save the page now I get an error because there is no entry selected for the link.

Only special case on my side is that the LinkIt field is placed within a SuperTable (https://github.com/engram-design/SuperTable).

Let me know if I can provide additional info.

Cheers,

Pascal.

**Comment by ChaseGiunta** [comment]
@superflausch just to clarify (and rule out my possible cause), you don't have any locales set up on your Craft site?

**Comment by superflausch** [comment]
@ChaseGiunta Sorry, I planned to add this info.

I do have multiple locales setup, two to be exact. The section, where the whole entry/page is saved is set to support only one of the locales (de). The surrounding SuperTable is set to be translatable (for additional future locales). But I use the CP in english (that's the other currently setup locale). Hope this helps.

**Comment by superflausch** [comment]
I just noticed that this is likely a Craft bug, at least for me.

As I mentioned the section is only available in German (de), but I have two locales setup (de/en). For some reason the CP shows me the EN locale of some translatable fields (not all), even if there should be only DE fields. This doesn't happen when I change the CP language to DE, there I get only DE locales fields and can save without an issue.

**Comment by ChaseGiunta** [comment]
I can't say I've experienced that, and it seems this is the only fieldtype, for me, that is having this problem- which leads me to believe that the plugin just hasn't been updated and/or tested for use in multi-locale setups.

**Comment by superflausch** [comment]
It looks like I'm able to see the correct LinkIt entry connections when I'm using the CP in the same language as the locale of the field. When I use the CP in another language as the locale I'm editing I don't see the associated entry in the LinkIt field.

**Comment by samhibberd** [comment]
This is something that we are aware of and hope you address in the next release, as a agency we are super busy at the moment and frustrating getting too little time to commit to our plugins. But rest assured it is on the list!!

**Comment by superflausch** [comment]
That's great to hear. Thanks a lot, appreciate it.

**Comment by samhibberd** [comment]
Fixed in the latest release, please make sure you backup and test out pre launch!
