### ISSUE TITLE
Labels and placeholders aren't translatable

### ISSUE THREAD

**Issue by thijskaspers** [fruitstudios/LinkIt#14]
Could you please take advantage of Craft's static translation support by running all text through "*|t" or Craft::t()? We see that some strings are translatable and other strings aren't.

Linkit is in English and we want to translate it to Dutch for a customer. Especially the select options (Email Address, Telephone Number, etc.) and field placeholders.

Thanks!

**Comment by wateengoedidee** [comment]
I have the same problem here. I would also appreciate it if you guys could make the static text translatable. 

Thanks in advance

**Comment by samhibberd** [comment]
We have completely rewritten the plugin which is due to be released shortly, no major changes to functionality, just improvements to the code base and the way data is stored and accessed, everything should be translatable now. 

Once release please let us know if we have missed anything!

**Comment by thijskaspers** [comment]
@samhibberd Do you have an ETA on the rewritten Linkit plugin?

**Comment by balazscsaba2006** [comment]
Do you have an ETA for the new version of the plugin?

**Comment by samhibberd** [comment]
Fixed in the latest release, please make sure you backup and test out pre launch!
