### ISSUE TITLE
‘link’ handle in readme is misleading

### ISSUE THREAD

**Issue by joshuabaker** [fruitstudios/LinkIt#15]
`link` is a reserved work so might be worth replacing the documentation.

This tripped me up when using SuperTable, which doesn’t validate handles (engram-design/SuperTable#19).

**Comment by sebastianthomas** [comment]
@joshuabaker Thanks for this! That was real fookin me up. Would never have thought of that.... 
:+1:

**Comment by samhibberd** [comment]
@joshuabaker What would you suggest, we are going to use the  __toString() method such that `{{ entry.yourLinkItField }}` will return the link html.

**Comment by joshuabaker** [comment]
I was just raising a minor semantical issue that I noticed in the readme, which assigns `entry.yourLinkItField` to a `link` variable within the template.

A few people have been tripped up by looking through the readme and using `link` as a field handle, a reserved word, for LinkIt fields within a SuperTable field.

**Comment by samhibberd** [comment]
Good call, i've updated the Readme.

**Comment by sidneywidmer** [comment]
+1, any updates on this?

**Comment by joshuabaker** [comment]
@sidneywidmer: See 6cb36fde7c401ff5272766919e725b72a2bf6230, a97223d177780d5b8fb396f1aa667cc90a35363c, and d46f87a6c2d26fb41bec5d392c1ecd7b96ef0805

**Comment by sidneywidmer** [comment]
shit sorry, posted my comment on the wrong issue :) I was talking about the one with the localization, probably it was a bit too early for me

**Comment by samhibberd** [comment]
```link``` will be removed in the upcoming update

**Comment by samhibberd** [comment]
Fixed in the latest release, please make sure you backup and test out pre launch!
