### ISSUE TITLE
Selection label

### ISSUE THREAD

**Issue by ianisted** [fruitstudios/LinkIt#16]
Are there any plans to support custom selection labels? Renaming from "Add an asset" to "Add an image" is a big help to UX.

Love the plugin. Thanks :)

**Comment by samhibberd** [comment]
Nice idea yes, update is coming soon!!!

**Comment by ianisted** [comment]
Fantastic! Thanks :+1:

**Comment by samhibberd** [comment]
Fixed in the latest release, please make sure you backup and test out pre launch!
