### ISSUE TITLE
Exclude sections that don’t have URLs

### ISSUE THREAD

**Issue by joshuabaker** [fruitstudios/LinkIt#18]
Might it make sense to prevent selection of entries within sections that do not have URLs?

```php
/**
 * Returns all sections that have URLs.
 *
 * @return array An array of Section instances
 */
public function getSectionsWithUrls()
{
    return array_filter(craft()->sections->allSections, function ($section) {
        return $section->isHomepage() || $section->urlFormat;
    });
}
```
<sup>[Source](https://github.com/joshuabaker/craft-sitemap/blob/331d476a5c7cdf305b81e9e3bea18c8f027fd425/sitemap/services/SitemapService.php#L24-L34)</sup>

**Comment by samhibberd** [comment]
Thanks for the feedback, this will be included in an upcoming rewrite to the plugin which is due to be released shortly, no major changes to functionality, just improvements to the code base and the way data is stored and accessed.

**Comment by samhibberd** [comment]
Fixed in the latest release, please make sure you backup and test out pre launch!

**Comment by joshuabaker** [comment]
:+1: Thanks.
