### ISSUE TITLE
Add support for more than 1 link

### ISSUE THREAD

**Issue by bakura10** [fruitstudios/LinkIt#19]
Hi,

First of all, thank you for your plugin. It solves a common issue that Craft has.

The only drawback compared to the built-in "entries" field is that LinkIt does not allow to add more than one link. It would be nice is, as of the built-in entries, you could enforce a limit, but allow to add more than 1 link.

Thanks!

**Comment by samhibberd** [comment]
Hmm, i'm not sure that this is something we would integrate as this could be easily be achieved using matrix. Unless you can suggest a use case that i'm missing??

**Comment by bakura10** [comment]
Hi,

Sure, there is a very specific use case I'm facing (and that seems common enough to justify the need for it). I've explained it in the Craft forum: http://craftcms.stackexchange.com/questions/11425/create-a-link-list-with-urls-categories-entries/11444#11444

To summarize it, imagine a footer, where you have several block with title + list of links. If LinkIt would allow multiple links, you could simply create one matrix with a block called "linklists", that would contain the title and LinkIt field (to add unlimited links).

Because LinkIt only allow one link, I need to do something more complex:

1. create one matrix with one block that contains a title field, and one block that contain the linkIt field.

This is much less flexible, because I would need to create one matrix field per linklist I want in my footer.

Hope it's clear :)

**Comment by samhibberd** [comment]
Unless we can come up with a really decent use case, i think Link It is going to remain a single link fieldtype??

**Comment by theleyley** [comment]
It would be create if there's a solution for this. I'd love to add multiple linkit entires within a matrix. This solves my "matrix in a matrix" problem that many people seem to be asking for! This is a great plugin - if only it had that 1 feature!

**Comment by benjamminf** [comment]
@theleyley If you haven't already seen this plugin, [SuperTable](https://github.com/engram-design/SuperTable) can solve your Matrix-in-Matrix issue. I use LinkIt fields inside a SuperTable field inside a Matrix block and it works very well.

Alternatively, (shameless plug) you could wait for my latest plugin [Neo](https://github.com/benjamminf/craft-neo) which could also accomplish this but in a different way.

**Comment by samhibberd** [comment]
@theleyley sorry but not something we will be adding anytime soon if at all. Agree with @benjamminf there are lots of tools which can help out there and really like the look of Neo, great to see it hit 1.0!!
