### ISSUE TITLE
"Custom Url" field requests "Please enter a valid url" although field is not marked as required

### ISSUE THREAD

**Issue by phaetons** [fruitstudios/LinkIt#20]
I added a LinkIt field with "custom Url" to my Entries, if i save the entry and the custom url is empty, the field claims: "Please enter a valid url". But the field is not marked as required.
Same problem if i choose "entry" link-type.

**Comment by phaetons** [comment]
The problem occurs only, if you choose just to display one link-type and the field for it is displayed directly and not the selectbox to choose a linktype from.

**Comment by tomkiss** [comment]
Just to say I'm also seeing this bug - thanks for the info, nice workaround for now.

**Comment by sg-modlab** [comment]
Seeing this issue as well.

**Comment by samhibberd** [comment]
Fixed in the latest release, please make sure you backup and test out pre launch!
