### ISSUE TITLE
Craft Beta 2.5 Compatibility

### ISSUE THREAD

**Issue by ianshea** [fruitstudios/LinkIt#21]
Within a Matrix Block, the configuration of the field is rendering out HTML.

![screenshot 2015-11-06 12 09 26](https://cloud.githubusercontent.com/assets/673992/11007526/52c2ff50-847f-11e5-9413-6bdd7f21a9dd.png)

**Comment by mildlygeeky** [comment]
I am also seeing this, though just in field setup (not in the context of a Matrix block).

**Comment by samhibberd** [comment]
We are working on the 1.0 release with support for 2.5.

**Comment by mildlygeeky** [comment]
Awesome, thanks, and thank you for this great plugin!

**Comment by irock195** [comment]
Yeah! Thanks guys, this is a great plugin.

**Comment by samhibberd** [comment]
Thanks gents, we are looking at ways to tweak improve the ui, is there anything you would like to see improved / changed / added.

**Comment by joshangell** [comment]
Is there any eta on 1.0?

**Comment by ben-callaway** [comment]
Hello,

I'm out of the office on annual leave, back Monday 7th December. All emails will be dealt with on my return.

If you do have anything urgent, please don’t hesitate to get in contact with Sam on 01962 809 103 | sam@fruitstudios.co.uk.

Thank you.

Kind regards,
Ben Callaway
 
Fruit Studios Ltd
First Floor
100 High Street
Winchester
Hampshire
SO23 9AH
 
T: 01962 809 103 
E: ben@fruitstudios.co.uk
W: www.fruitstudios.co.uk

====================================================

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify Fruit Studios Ltd immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Fruit Studios Ltd does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. Opinions expressed in this email are those of Ben Callaway, and do not necessarily reflect those of Fruit Studios Ltd. If verification is required please request a hard-copy version.

====================================================

**Comment by theskyfloor** [comment]
Any chance you are going to support Element Index customization output for 2.5?

**Comment by samhibberd** [comment]
@joshangell I am working on it this weekend! Client work has been crazy the last few months. The biggest challenge is writing the migration tools as there are breaking changes behind the scenes.

@theskyfloor yes!! but not initially.

Sam

**Comment by thijskaspers** [comment]
@samhibberd Any updates/ETA on v1.0? We are using Linkit on a couple of websites and want to update to Craft 2.5

**Comment by samhibberd** [comment]
Guys, I have v2.0 ready to roll although I just haven't had time to work on the migration for 2.5 or the docs, the new version has breaking changes and improved twig stuff!

Would people prefer i just release so they can manually update for now??

**Comment by benjamminf** [comment]
I'd really appreciate the release now as I'm building all new sites on 2.5 and have postponed past sites from updating. That said, I just installed the current version of LinkIt on 2.5 yesterday and have not encountered this or any other issue.

Huge props for your effort mate! You've made my work so much easier with this plugin :+1:

**Comment by bgarrant** [comment]
So are we 2.5 compatible with the current .91 version?

**Comment by samhibberd** [comment]
As far as i'm aware, with the exceptions of the locale issues in the field settings, its all good for 2.5.

2.0 is a complete rewrite and requires some template changes and a change to the way the data is stored in the Craft DB. I had a slack with brandon yesterday and he has helped out loads with the migration stuff, which is nearly finished!!

I'm on holiday next week, this means plugin dev!!!

**Comment by theskyfloor** [comment]
Exciting! Does 2 have new features besides refactoring the code?

**Comment by bgarrant** [comment]
Thanks so much. This is my fav plugin now! Makes setting up navigation with a Structure section a snap

**Comment by page-8** [comment]
Hi @samhibberd, thanks for the incredibly useful plugin (which the by product is this thread ;-)

Any ETA on the 2.5 update? Thanks!

**Comment by samhibberd** [comment]
This week for sure!

**Comment by page-8** [comment]
Awesome, thanks for the update!

**Comment by brianckaufman** [comment]
We are looking forward to the update! On hold to update client to Craft 2.5. Thanks!

**Comment by johanneslamers** [comment]
"This week for sure!...." any ETA?

**Comment by samhibberd** [comment]
You got me. Sorry client work has to take priority. It's done, just need to update the read me and release.

**Comment by thijskaspers** [comment]
@samhibberd Any idea when you'll do this? Just as @brianckaufman we are also on hold to update multiple clients to Craft 2.5. Thanks in advance!

**Comment by samhibberd** [comment]
@thijskaspers @brianckaufman the old version of linkit is compatible with 2.5, just locale settings are not available. I will get the docs and plugin updated this week.

**Comment by thijskaspers** [comment]
@samhibberd I know, but the sites are already using Linkit, so we need the migrations in order to not lose any data ;)

**Comment by samhibberd** [comment]
@thijskaspers You shouldn't, the migrations i have written are only required when you update to the new version. 

Please do backup before trying though. I have had no issues running linkit 0.9.1 on 2.5.

**Comment by thijskaspers** [comment]
@samhibberd Ah of course, roger that ;)

**Comment by brianckaufman** [comment]
@samhibberd hey Sam, I know you've got to be busy, but, just checking in on locale support update?

**Comment by samhibberd** [comment]
Released, finally, please make sure you backup and test out pre launch!

**Comment by brianckaufman** [comment]
Awesome, thanks Sam!


On February 28, 2016 at 5:49:29 AM, Sam Hibberd (notifications@github.com) wrote:

Closed #21.
