### ISSUE TITLE
Changing entry status removes link

### ISSUE THREAD

**Issue by outhouse** [fruitstudios/LinkIt#22]
I'm not sure if this has been asked yet, or if perhaps I'm missing something.

I've noticed that if an entry status is changed to inactive, this will remove the entry from any associated LinkIt fields.

If I later on change that entry back to active, to restore the link, I have to return to any associated LinkIt fields, and relink to that entry. 

It would be ideal if status changes did not remove the link association.

**Comment by samhibberd** [comment]
This issue has been resolved in the new version, still fixing the last few issues before getting a release out.

**Comment by outhouse** [comment]
Thanks. Looking forward to the new release.
