### ISSUE TITLE
Open in new window not saving

### ISSUE THREAD

**Issue by danielparas** [fruitstudios/LinkIt#24]
Hi, thanks for this great plugin!

Just updated to the latest version and when clicking the "open in new window" checkbox and saving the entry, the option does not hold - i.e. entry.linkitfield.target is not set. Also when in the entry editor again, the checkbox will not be ticked.

Thanks in advance!
Dan

**Comment by samhibberd** [comment]
Ok Dan, I will take a look for you, any errors in the Craft logs? `/admin/utils`

**Comment by samhibberd** [comment]
Recreated here, will fix today!

**Comment by samhibberd** [comment]
Fixed in 2.3.1

**Comment by danielparas** [comment]
thanks for the super quick response @samhibberd !
