### ISSUE TITLE
How to make Link It do Breadcrumbs?

### ISSUE THREAD

**Issue by bgarrant** [fruitstudios/LinkIt#26]
I have a site using a Structure section with a single Link It field for navigation.  The field is called "navigationEntry" and links Entries, Assets and Categories. How can I get it to go breadcrumbs?  It does not seem to work with relationships so how can I get this code below to work?  It does not really output anything.  What am I missing?

```
{% set bread = craft.entries.section('mainNavigation').relatedTo(entry.navigationEntry.entry).first %}

<nav class="breadcrubs">
    <ol class="breadcrumb">
        <li><a href="{{ siteUrl }}">Home</a></li>
       		
	    {% for crumb in bread.getAncestors %}
        	<li>{{ crumb.navigationEntry.html }}</li> 
        {% endfor %}

		<li>{{ bread.title }}</li>

    </ol>
</nav>
```

**Comment by samhibberd** [comment]
Have you got this working? I will need a little bit of info to help, but I suspect it is more of a Craft Twig thing than Link It.

**Comment by bgarrant** [comment]
I was unable to make LinkIt work with a breadcrumb format. I actually talked the client into not using the breadcrumbs for now, but we would like to use that feature in future.

 

Bryan Garrant

Garrant Consulting LLC

518.327.5159

**Comment by samhibberd** [comment]
There is no reason i can see it no working with the structure, all Link It does is return the entry / category / asset that is being linked to. Surely in this case you actually want the id on the structure entry to grab the ancestors? Unless i'm missing something? 

Let me know if it comes up again and i will take a look.

**Comment by bgarrant** [comment]
I must just have a coding issue getting the ID.  I will try a few other methods.

 

Bryan Garrant

Garrant Consulting LLC

518.327.5159
