### ISSUE TITLE
Access new window variable?

### ISSUE THREAD

**Issue by jacobgraf** [fruitstudios/LinkIt#36]
I am using Link It to output a URL for an image link but how do I output the target="_blank" for a link that I'm manually templating using the link URL? If it's not already built in somehow, I would love to be able to access entry.field.target and have it output _blank or _self based on what the user sets the option to.

**Comment by samhibberd** [comment]
`target="{{ entry.linkItField.target ? entry.linkItField.target : '_self' }}"`

**Comment by jacobgraf** [comment]
SMH - I swear I read the docs before I submitted the question. Thanks and sorry!
