### ISSUE TITLE
Error when CMS is running re-save entries task.

### ISSUE THREAD

**Issue by a-am** [fruitstudios/LinkIt#4]
I keep getting this error in the phperrors log when Craft is running it's re-save entries task.  It appears thhis stops the task from completing. 
`Call to a member function getUrl() on a non-object in Linkit_LinkitFieldType.php on line 384.`
I am running Craft Pro 2.2.2588.

**Comment by samhibberd** [comment]
Fixed in the latest release, please make sure you backup and test out pre launch!
