### ISSUE TITLE
Writing Plugin with linkit_registerElementTypes and linkit_getElementData

### ISSUE THREAD

**Issue by crookedneighbor** [fruitstudios/linkit#45]
I'm having trouble understanding how to use the [`linkit_getElementData` hook](https://github.com/fruitstudios/LinkIt/blob/909bdcd03cd385f532387053a82938269afc97b7/README.md#linkit_getelementdata). Do you have an example plugin that uses it?

Specifically, I'm having trouble with the `myPlugin_myElements` bit in `$myElement = craft()->myPlugin_myElements->getMyElementById($id);`. Is `myPlugin_myElements` supposed to be my plugin's name? In that case, should I be implementing my own public `getMyElementById` method? Or how does it work? I keep running into Exceptions when I try to use it.

**Comment by crookedneighbor** [comment]
@joshangell do you have an example repo that shows how to make a plugin?

**Comment by Moorst** [comment]
Did you ever get anywhere with this? I'm hoping to add the https://venticalendar.io/ event type (Venti_Event) to Link It and not sure how to do so.

**Comment by crookedneighbor** [comment]
Never got anywhere.

**Comment by Moorst** [comment]
This ended up working for me;
`$myElement = craft()->elements->getElementById($id);`
