### ISSUE TITLE
Only output href

### ISSUE THREAD

**Issue by warrebuysse** [fruitstudios/LinkIt#65]
Is it possible to only put the href? I would like to do something like the following:
```
<a href="{{ cat.link.linkItField }}" class="categories__item__cta">
```

Alternatively is it possible to add the element as a wrapper?
Something like this:
```
{{ linkItField.beginningHere }}
	<div class="categories__item__background-wrapper">
		<img src="http://unsplash.it/500/500" alt="" class="categories__item__background" />
	</div>
	<div class="categories__item__button"><span class="standard">{{ cat.titel }}</span><span class="hover">Meer info</span></div>
	<div class="categories__item__overlay">
		<h2 class="categories__item__overlay__title title--stroked title--stroked--center">{{ cat.titel }}</h2>
		<div class="typography typography--light typography--14">
			<p>{{ cat.inhoud }}</p>
		</div>
	</div>
{{ linkItField.endHere }}
```

**Comment by samhibberd** [comment]
@warrebuysse the {{ linkItField }} variable returns a link model which allows you to access the url `{{ linkItField.url }}` along with everything else related to the link (type, target, url, text).

See: https://github.com/fruitstudios/LinkIt#template-variables-advanced-use
