### ISSUE TITLE
Error on localized site

### ISSUE THREAD

**Issue by robbiepost** [fruitstudios/LinkIt#7]
Getting template errors (Impossible to access an attribute ("url") on a boolean variable ("")) while using this tag on the second language on a localized site. In my case my-domain.nl/en/
  
							<a href="{{ link.url }}" {{ link.target ? ' target="_blank"' }} title="{{ link.linkText }}"
								class="tp-caption sfb skewtotop btn btn-link"
								data-x="{{ block.linkXPosition}}"
								data-y="{{ block.linkYPosition}}"
								data-speed="1000"
								data-start="2000"
								data-easing="Power4.easeOut"
								data-endspeed="400"
								data-endeasing="Power1.easeIn">
								{{ link.linkText }} <i class="fa fa-angle-right"></i>
							</a>

**Comment by samhibberd** [comment]
We have completely rewritten the plugin which is due to be released shortly, no major changes to functionality, just improvements to the code base and the way data is stored and accessed, should make this easier to template.
