### ISSUE TITLE
Link opens in new window when target isn't set

### ISSUE THREAD

**Issue by artmem** [fruitstudios/linkit#72]
My code:
`	{% set attributes = {
	    target: 'block.button.target',
	    class: 'button centered'
	} %}
	{{ block.button.htmlLink(attributes) }}`
When "Open link in new window?" is checked, the target is set to _blank, and it works properly. However, when the box is not checked, the target attribute is set to 'block.button.target' and the link opens in a new window, anyway.

**Comment by kmauric** [comment]
remove the single quotes from your target attribute, so it will just be `block.button.target`
