### ISSUE TITLE
Linkit only returns a string variable

### ISSUE THREAD

**Issue by bartbrusselmans** [fruitstudios/linkit#75]
Hi,

I'm running into an issue where I can not access my LinkIt field's attributes. This being because the field is returning a string variable. Any help would be appreciated. Here is my code.

```
{% for blocks in entry.threeWidgets %}
    <div class="four columns">
      <div class="box box--border">
        <h3>{{ blocks.title }}</h3>
        <p>
          {{ blocks.bodyContent }}
        </p>
        <a href="{{ blocks.buttonLinkOne.url }}" class="button">{{ blocks.buttonLinkOne.text }}</a>
      </div>
    </div>
{% endfor %}
```

Thanks

**Comment by brandondeweese** [comment]
`{# if entry.linkItField.type is defined #}
<a href="{{ entry.linkItField.url }}" class="btn btn-primary btn-color">{{ entry.linkItField.text }}</a>
 {% endif %}`
