### ISSUE TITLE
getThirdPartyElementData not found

### ISSUE THREAD

**Issue by McCrisp** [fruitstudios/linkit#76]
I keep getting the error:

> Craft\FruitLinkIt_LinkModel and its behaviors do not have a method or closure named "getThirdPartyElementData".

Using the newest version of craft, and trying to use the field together with Neo fields, if that helps.

**Comment by johndwells** [comment]
We've just encountered this. I've submitted a pull request with what I believe is the fix: https://github.com/fruitstudios/LinkIt/pull/78
