### ISSUE TITLE
Force download option.

### ISSUE THREAD

**Issue by monachilada** [fruitstudios/LinkIt#8]
How would you go about the force download option? Is that something you could achieve with twig `{% header %}` tags alone? I'm stumbling on how to include the raw contents of the file after the headers with twig...

    {% header 'Content-Description: File Transfer' %}
    {% header 'Content-Type: '~asset.mimetype %}
    {% header 'Content-Disposition: attachment; filename='~asset.filename %}
    {% header 'Content-Transfer-Encoding: binary' %}
    {% header 'Expires: 0' %}
    {% header 'Cache-Control: must-revalidate' %}
    {% header 'Pragma: public' %}
    {% header 'Content-Length: '.asset.size %}
    {# Somehow print raw source of asset.filename #}

(Also, I swear I just stumbled upon this through a Google search, but so weird that we found each other's plugins on the same day and are each requesting features)

**Comment by samhibberd** [comment]
Small world! I should think this is more a twig thing, but if there is anything that I can do to help plugin side just let me know? 

In the past I have used a plugin called Safelink,by Ben from DUKT / P&T :), although i'm not sure what plans he has for it.

**Comment by monachilada** [comment]
Thanks Sam. I'm giving this a try, seems like it should do the job.
https://github.com/masonn/craft-yii-sendfile

**Comment by samhibberd** [comment]
Where about's are you based? It would be good to catch up and talk Craf / PHP dev, we have projects coming out of our ears it would be good to talk?

**Comment by monachilada** [comment]
I'm in Berlin, where are you guys? Would be very happy to talk, let's set up a Skype chat? Send me an email if you like: mike (at) someoneandsons.net.

**Comment by samhibberd** [comment]
Is this something that you still feel would be beneficial to this field type?

**Comment by monachilada** [comment]
Sure, why not!?
I think in the end I used this plugin to achieve the effect, maybe you can draw some inspiration there? https://github.com/masonn/craft-yii-sendfile

**Comment by samhibberd** [comment]
On the roadmap.
