### ISSUE TITLE
fieldhandle.type returns a long string

### ISSUE THREAD

**Issue by darylknight** [fruitstudios/LinkIt#89]
I'm trying to show a different icon depending on whether the user has selected "URL" or "Asset" for the linkit type. If I call `{{ entry.fieldhandle.type }}` in the template, I'd expect to get `url` or `asset`, but I'm getting this:

`fruitstudios\linkit\models\Url`
`fruitstudios\linkit\models\Asset`

**Comment by samhibberd** [comment]
@darylknight looks like you are on the Craft 3 version? Can we move this over to the Craft 3 Github page: https://github.com/fruitstudios/craft-linkit

**Comment by darylknight** [comment]
Got it, sorry!
