### ISSUE TITLE
Remove dropdown when only single option available

### ISSUE THREAD

**Issue by engram-design** [fruitstudios/LinkIt#9]
Would be a great idea to remove (or hide) the dropdown box when only one option to select is available. For instance, if the user can only select Entries. I think it'd clean things up a little - but of course would need it there if more than one option.

![screen shot 2015-02-21 at 12 48 07 am](https://cloud.githubusercontent.com/assets/1221575/6287159/53e30480-b963-11e4-9cef-35fa58495d80.png)

**Comment by samhibberd** [comment]
Absolutely, this one is on my list. It's a priority to improve the UI, i'm hoping to get some time on this one soon!

**Comment by samhibberd** [comment]
Done, hope this helps, let me know if you run into any issues.

**Comment by engram-design** [comment]
Perfect, thanks!
