### ISSUE TITLE
Type method in the LinkIt model doesn't return what it's supposed to

### ISSUE THREAD

**Issue by petehjfd** [fruitstudios/LinkIt#91]
The readme suggests that the type method in the LinkIt model (e.g. `{{ entry.linkItField.type }}`) should return one of the following: `email`, `custom`, `tel`, `entry`, `category` or `asset`.

But it actually returns:

`fruitstudios\linkit\models\Asset`, `fruitstudios\linkit\models\Entry`, etc

**Comment by samhibberd** [comment]
Hey @petehjfd, this is the repo for the Craft 2 version, if you are on the Craft 3 version (which it looks like you are) you will need to use the `{{ entry.linkItField.typeHandle }}` see the [new docs](https://github.com/fruitstudios/craft-linkit/blob/master/README.md#using-linkit)
