### ISSUE TITLE
Plugin fails to install on Craft 3.1

### ISSUE THREAD

**Issue by jripmeester** [fruitstudios/LinkIt#94]
On upgrading one of my websites to Craft 3.1 the LinkIt Plugin fails to install.

On install the plugin tries to select id and settings column from the plugins table. Except as of Craft 3.1 the settings column is no longer in the plugin table.

**Comment by samhibberd** [comment]
@jripmeester this is the repo for the Craft 2 version of Linkit, can you post the issue over [here](https://github.com/fruitstudios/craft-linkit/issues), 3.1 will be supported in Linkit 2.1
