### ISSUE TITLE
No trial for Craft 3

### ISSUE THREAD

**Issue by Delonvdv** [fruitstudios/LinkIt#95]
Is there no trial version of this for Craft 3?

**Comment by samhibberd** [comment]
There should be, i'm currently fixing a few issues with the migration / install process for 3.1 and will make sure this is available to.

**Comment by Delonvdv** [comment]
Thanks for the quick response? Any idea when it would be available?

**Comment by samhibberd** [comment]
Hopefully today.

**Comment by samhibberd** [comment]
This is a know issue with Craft 3.1, its been raised and fixed see: https://github.com/craftcms/cms/issues/3642
